name: install_all_ubuntu_deps
runs:
  using: composite
  steps:
  - name: Install cmake
    run: |-
      echo $(date +%F) > ./date
      echo $(git ls-remote https://github.com/facebookresearch/habitat-lab.git HEAD | awk '{ print $1}') > ./hablab_sha
      cat ./hablab_sha
      wget https://cmake.org/files/v3.12/cmake-3.12.4-Linux-x86_64.sh
      wget https://cmake.org/files/v3.20/cmake-3.20.1-linux-x86_64.sh
      sudo mkdir /opt/cmake312
      sudo mkdir /opt/cmake320
      sudo sh ./cmake-3.12.4-Linux-x86_64.sh --prefix=/opt/cmake312 --skip-license
      sudo sh ./cmake-3.20.1-linux-x86_64.sh --prefix=/opt/cmake320 --skip-license
      sudo ln -s /opt/cmake312/bin/cmake /usr/local/bin/cmake
    shell: bash
  - name: Install dependencies
    run: |-
      sudo apt-get update || true
      sudo apt-get install -y --no-install-recommends \
          build-essential \
          git \
          curl \
          vim \
          ca-certificates \
          libjpeg-dev \
          libglm-dev \
          libegl1-mesa-dev \
          ninja-build \
          xorg-dev \
          freeglut3-dev \
          pkg-config \
          wget \
          zip \
          lcov\
          libhdf5-dev \
          libomp-dev \
          unzip || true
    shell: bash
  - name: Install Headless Chrome dependencies
    run: |-
      sudo apt-get update || true
      sudo apt-get install -yq \
            gconf-service \
            libasound2 \
            libatk1.0-0 \
            libatk-bridge2.0-0 \
            libc6 \
            libcairo2 \
            libcups2 \
            libdbus-1-3  \
            libexpat1 \
            libfontconfig1 \
            libgcc1 \
            libgconf-2-4 \
            libgdk-pixbuf2.0-0 \
            libglib2.0-0 \
            libgtk-3-0 \
            libnspr4 \
            libpango-1.0-0 \
            libpangocairo-1.0-0 \
            libstdc++6 \
            libx11-6 \
            libx11-xcb1 \
            libxcb1 \
            libxcomposite1 \
            libxcursor1 \
            libxdamage1 \
            libxext6 \
            libxfixes3 \
            libxi6 \
            libxrandr2 \
            libxrender1 \
            libxss1 \
            libxtst6 \
            ca-certificates \
            fonts-liberation \
            libappindicator1 \
            libnss3 \
            lsb-release \
            xdg-utils \
            wget
    shell: bash
  - name: Install cuda
    run: |-
      # sudo apt-key adv --fetch-keys "https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64/7fa2af80.pub"
      # sudo apt-add-repository "deb https://developer.download.nvidia.com/compute/cuda/repos/ubuntu2004/x86_64 /"
      # sudo apt-get update || true
      # sudo apt-get --yes --force-yes install cuda-11-1
      touch ~/cuda_installed
      if command -v nvidia-smi; then nvidia-smi; fi
    shell: bash
  - name: restore_cache
    uses: actions/cache@v3.3.2
    with:
      key: conda-{{ checksum "habitat-sim/.circleci/config.yml" }}-{{ checksum "./date" }}
      path: UPDATE_ME
      restore-keys: conda-{{ checksum "habitat-sim/.circleci/config.yml" }}-{{ checksum "./date" }}
  - name: Setup miniconda
    uses: conda-incubator/setup-miniconda@v3.0.1
    with:
      auto-activate-base: true
      activate-environment: ""
  - name: Install conda and dependencies
    run: |-
      # For whatever reason we have to install pytorch first. If it isn't
      # it installs the 1.4 cpuonly version. Which is no good.
      conda install -y pytorch==1.12.1=py3.9_cuda11.3_cudnn8.3.2_0 torchvision==0.13.1=py39_cu113 cudatoolkit=11.3 -c pytorch -c nvidia
      conda install -y -c conda-forge ninja numpy pytest pytest-cov ccache hypothesis pytest-mock
      pip install pytest-sugar pytest-xdist pytest-benchmark opencv-python cython mock
    shell: bash
  - name: Validate Pytorch Installation
    run: |-
      # Check that pytorch is installed with CUDA.
      export PATH=$HOME/miniconda/bin:$PATH
      . activate habitat;
      python -c 'import torch; torch.cuda.set_device(0)'
    shell: bash
  - name: Install emscripten
    run: |-
      if [ ! -f ~/emscripten_installed ]
      then
        export PATH=$HOME/miniconda/bin:$PATH
        . activate habitat;
        git clone -q https://github.com/emscripten-core/emsdk.git ~/emsdk
        cd ~/emsdk
        ./emsdk install 1.38.48
        ./emsdk activate 1.38.48
        . ~/emsdk/emsdk_env.sh
        touch ~/emscripten_installed
      fi
    shell: bash
  - name: Install JavaScript dependencies
    run: |-
      if [ ! -f ~/npm_deps_installed ]
      then
        wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.34.0/install.sh | bash
        . ~/.bashrc
        nvm install v11.9.0
        nvm use v11.9.0
        npm install
        touch ~/npm_deps_installed
      fi
    shell: bash
  - name: restore_cache
    uses: actions/cache@v3.3.2
    with:
      key: ccache-{{ arch }}-{{ .Branch }}-{{ .BuildNum }}
      path:
      - "/home/circleci/.ccache"
      restore-keys: |-
        ccache-{{ arch }}-{{ .Branch }}-{{ .BuildNum }}
        ccache-{{ arch }}-{{ .Branch }}-
        ccache-{{ arch }}-main-
  - name: CCache initialization
    run: |-
      export PATH=$HOME/miniconda/bin:$PATH
      . activate habitat;
      ccache --show-stats
      ccache --zero-stats
      ccache --max-size=10.0G
    shell: bash